[DOCUMENTATION]
org_name = "Carrier Inspiration Ministries"
org_url = "https://denim-firewall-da7.notion.site/Hello-I-m-Bryce-Nathanial-Carrier-1497a0361320802cbfdbe4db04f8deac"
org_description = "A faith-based mission working to strengthen the church connection between the USA and Zambia through PNEUMA, a Christian token of generosity and Gospel purpose."

[[CURRENCIES]]
code = "PNEUMA"
issuer = "GAR43MR2JNU2AZZPGJZ7TTB6PCPBQZLQ5Z5I3ETNXM5YH73KJZYX64GJ" 
display_decimals = 2
name = "PNEUMA Coin"
desc = "A Christian token designed to connect the Church in the USA and Zambia through generosity and decentralized giving."
image = "https://pneumacoin.github.io/pneuma-logo.png"
status = "live"

[[CURRENCIES]]
code = "CIMCO"
issuer = "GARWXOINWTEWUU4JH3XCDGIDNAYXEILOOKSKZDVOUM6WRC4FO7XM3SKP"
display_decimals = 7
image = "https://pneumacoin.github.io/cimco/CIMCO-logo.png"
desc = "CIMCO is the market-facing token that pumps global value into PNEUMA for ministry through the VESSEL app."
status = "live"